name: R-CMD-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.1.1', '4.2.1']

    steps:
      - uses: actions/checkout@v4

      # Set up R with the specified version
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      # Set up Pandoc
      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-base \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-latex-recommended \
            texlive-extra-utils \
            texlive-latex-extra \
            qpdf

      # Install R package dependencies
      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      # Check R package
      - name: Check R package
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
