name: R-CMD-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.1.0', '4.2.0']

    steps:
      - uses: actions/checkout@v4

      # Configurar R con la versión especificada y usar RSPM para binarios
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          use-public-rspm: true  # Utiliza RSPM para obtener paquetes binarios

      # Instalar dependencias del sistema necesarias para `arrow`
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff-dev \
            libjpeg-dev

      # Instalar el paquete `arrow` utilizando binarios
      - name: Install 'arrow' package
        run: |
          options(install.packages.check.source = "no")
          install.packages("arrow", type = "binary")
        shell: Rscript {0}

      # Instalar dependencias del paquete en R utilizando binarios
      - name: Install R package dependencies
        run: |
          options(install.packages.check.source = "no")
          install.packages(c("remotes", "rcmdcheck"), type = "binary")
          remotes::install_deps(dependencies = TRUE, upgrade = "always", type = "binary")
        shell: Rscript {0}

      # Verificar el paquete con rcmdcheck
      - name: Check R package
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-build-vignettes"), error_on = "error")
        shell: Rscript {0}
